// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: messages.proto

package typedefs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Instruction_ShareInst
	//	*Instruction_ReconstructInst
	Op            isInstruction_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Instruction) GetOp() isInstruction_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Instruction) GetShareInst() *Message_Share {
	if x != nil {
		if x, ok := x.Op.(*Instruction_ShareInst); ok {
			return x.ShareInst
		}
	}
	return nil
}

func (x *Instruction) GetReconstructInst() *Message_Reconstruct {
	if x != nil {
		if x, ok := x.Op.(*Instruction_ReconstructInst); ok {
			return x.ReconstructInst
		}
	}
	return nil
}

type isInstruction_Op interface {
	isInstruction_Op()
}

type Instruction_ShareInst struct {
	ShareInst *Message_Share `protobuf:"bytes,3,opt,name=share_inst,json=shareInst,proto3,oneof"`
}

type Instruction_ReconstructInst struct {
	ReconstructInst *Message_Reconstruct `protobuf:"bytes,4,opt,name=reconstruct_inst,json=reconstructInst,proto3,oneof"`
}

func (*Instruction_ShareInst) isInstruction_Op() {}

func (*Instruction_ReconstructInst) isInstruction_Op() {}

type Message_Share struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Si            []byte                 `protobuf:"bytes,1,opt,name=si,proto3" json:"si,omitempty"`
	Ri            []byte                 `protobuf:"bytes,2,opt,name=ri,proto3" json:"ri,omitempty"`
	Idx           int64                  `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Share) Reset() {
	*x = Message_Share{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Share) ProtoMessage() {}

func (x *Message_Share) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Share.ProtoReflect.Descriptor instead.
func (*Message_Share) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Share) GetSi() []byte {
	if x != nil {
		return x.Si
	}
	return nil
}

func (x *Message_Share) GetRi() []byte {
	if x != nil {
		return x.Ri
	}
	return nil
}

func (x *Message_Share) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type Message_Reconstruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Si            []byte                 `protobuf:"bytes,1,opt,name=si,proto3" json:"si,omitempty"`
	Ri            []byte                 `protobuf:"bytes,2,opt,name=ri,proto3" json:"ri,omitempty"`
	Idx           int64                  `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Reconstruct) Reset() {
	*x = Message_Reconstruct{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Reconstruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Reconstruct) ProtoMessage() {}

func (x *Message_Reconstruct) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Reconstruct.ProtoReflect.Descriptor instead.
func (*Message_Reconstruct) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_Reconstruct) GetSi() []byte {
	if x != nil {
		return x.Si
	}
	return nil
}

func (x *Message_Reconstruct) GetRi() []byte {
	if x != nil {
		return x.Ri
	}
	return nil
}

func (x *Message_Reconstruct) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\btypedefs\"\x85\x01\n" +
	"\aMessage\x1a9\n" +
	"\x05Share\x12\x0e\n" +
	"\x02si\x18\x01 \x01(\fR\x02si\x12\x0e\n" +
	"\x02ri\x18\x02 \x01(\fR\x02ri\x12\x10\n" +
	"\x03idx\x18\x03 \x01(\x03R\x03idx\x1a?\n" +
	"\vReconstruct\x12\x0e\n" +
	"\x02si\x18\x01 \x01(\fR\x02si\x12\x0e\n" +
	"\x02ri\x18\x02 \x01(\fR\x02ri\x12\x10\n" +
	"\x03idx\x18\x03 \x01(\x03R\x03idx\"\x99\x01\n" +
	"\vInstruction\x128\n" +
	"\n" +
	"share_inst\x18\x03 \x01(\v2\x17.typedefs.Message.ShareH\x00R\tshareInst\x12J\n" +
	"\x10reconstruct_inst\x18\x04 \x01(\v2\x1d.typedefs.Message.ReconstructH\x00R\x0freconstructInstB\x04\n" +
	"\x02opB\fZ\n" +
	"./typedefsb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messages_proto_goTypes = []any{
	(*Message)(nil),             // 0: typedefs.Message
	(*Instruction)(nil),         // 1: typedefs.Instruction
	(*Message_Share)(nil),       // 2: typedefs.Message.Share
	(*Message_Reconstruct)(nil), // 3: typedefs.Message.Reconstruct
}
var file_messages_proto_depIdxs = []int32{
	2, // 0: typedefs.Instruction.share_inst:type_name -> typedefs.Message.Share
	3, // 1: typedefs.Instruction.reconstruct_inst:type_name -> typedefs.Message.Reconstruct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*Instruction_ShareInst)(nil),
		(*Instruction_ReconstructInst)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
