// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.9
// source: messages.proto

package typedefs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type View int32

const (
	View_VIEW_UNSPECIFIED View = 0
	View_UNDECIDED        View = 1
	View_ZERO             View = 2
	View_ONE              View = 3
	View_UNDECIDED_ZERO   View = 4
	View_UNDECIDED_ONE    View = 5
	View_ZERO_ONE         View = 6
)

// Enum value maps for View.
var (
	View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "UNDECIDED",
		2: "ZERO",
		3: "ONE",
		4: "UNDECIDED_ZERO",
		5: "UNDECIDED_ONE",
		6: "ZERO_ONE",
	}
	View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"UNDECIDED":        1,
		"ZERO":             2,
		"ONE":              3,
		"UNDECIDED_ZERO":   4,
		"UNDECIDED_ONE":    5,
		"ZERO_ONE":         6,
	}
)

func (x View) Enum() *View {
	p := new(View)
	*p = x
	return p
}

func (x View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (View) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (View) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use View.Descriptor instead.
func (View) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// Binary Value (BV) Message
type BVMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	SourceNode    int32                  `protobuf:"varint,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	BinValue      int32                  `protobuf:"varint,3,opt,name=bin_value,json=binValue,proto3" json:"bin_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BVMessage) Reset() {
	*x = BVMessage{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BVMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BVMessage) ProtoMessage() {}

func (x *BVMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BVMessage.ProtoReflect.Descriptor instead.
func (*BVMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *BVMessage) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BVMessage) GetSourceNode() int32 {
	if x != nil {
		return x.SourceNode
	}
	return 0
}

func (x *BVMessage) GetBinValue() int32 {
	if x != nil {
		return x.BinValue
	}
	return 0
}

// Auxiliary (Aux) Message
type AuxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	SourceNode    int32                  `protobuf:"varint,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	BinValue      int32                  `protobuf:"varint,3,opt,name=bin_value,json=binValue,proto3" json:"bin_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuxMessage) Reset() {
	*x = AuxMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxMessage) ProtoMessage() {}

func (x *AuxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxMessage.ProtoReflect.Descriptor instead.
func (*AuxMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AuxMessage) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *AuxMessage) GetSourceNode() int32 {
	if x != nil {
		return x.SourceNode
	}
	return 0
}

func (x *AuxMessage) GetBinValue() int32 {
	if x != nil {
		return x.BinValue
	}
	return 0
}

type AuxSetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	SourceNode    int32                  `protobuf:"varint,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	View          View                   `protobuf:"varint,3,opt,name=view,proto3,enum=typedefs.View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuxSetMessage) Reset() {
	*x = AuxSetMessage{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuxSetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuxSetMessage) ProtoMessage() {}

func (x *AuxSetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuxSetMessage.ProtoReflect.Descriptor instead.
func (*AuxSetMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *AuxSetMessage) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *AuxSetMessage) GetSourceNode() int32 {
	if x != nil {
		return x.SourceNode
	}
	return 0
}

func (x *AuxSetMessage) GetView() View {
	if x != nil {
		return x.View
	}
	return View_VIEW_UNSPECIFIED
}

type ABAEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ABAEnvelope_BvMsg
	//	*ABAEnvelope_AuxMsg
	//	*ABAEnvelope_AuxSetMsg
	Msg           isABAEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABAEnvelope) Reset() {
	*x = ABAEnvelope{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABAEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABAEnvelope) ProtoMessage() {}

func (x *ABAEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABAEnvelope.ProtoReflect.Descriptor instead.
func (*ABAEnvelope) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ABAEnvelope) GetMsg() isABAEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ABAEnvelope) GetBvMsg() *BVMessage {
	if x != nil {
		if x, ok := x.Msg.(*ABAEnvelope_BvMsg); ok {
			return x.BvMsg
		}
	}
	return nil
}

func (x *ABAEnvelope) GetAuxMsg() *AuxMessage {
	if x != nil {
		if x, ok := x.Msg.(*ABAEnvelope_AuxMsg); ok {
			return x.AuxMsg
		}
	}
	return nil
}

func (x *ABAEnvelope) GetAuxSetMsg() *AuxSetMessage {
	if x != nil {
		if x, ok := x.Msg.(*ABAEnvelope_AuxSetMsg); ok {
			return x.AuxSetMsg
		}
	}
	return nil
}

type isABAEnvelope_Msg interface {
	isABAEnvelope_Msg()
}

type ABAEnvelope_BvMsg struct {
	BvMsg *BVMessage `protobuf:"bytes,1,opt,name=bv_msg,json=bvMsg,proto3,oneof"`
}

type ABAEnvelope_AuxMsg struct {
	AuxMsg *AuxMessage `protobuf:"bytes,2,opt,name=aux_msg,json=auxMsg,proto3,oneof"`
}

type ABAEnvelope_AuxSetMsg struct {
	AuxSetMsg *AuxSetMessage `protobuf:"bytes,3,opt,name=aux_set_msg,json=auxSetMsg,proto3,oneof"`
}

func (*ABAEnvelope_BvMsg) isABAEnvelope_Msg() {}

func (*ABAEnvelope_AuxMsg) isABAEnvelope_Msg() {}

func (*ABAEnvelope_AuxSetMsg) isABAEnvelope_Msg() {}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\btypedefs\"d\n" +
	"\tBVMessage\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\x05R\n" +
	"sourceNode\x12\x1b\n" +
	"\tbin_value\x18\x03 \x01(\x05R\bbinValue\"e\n" +
	"\n" +
	"AuxMessage\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\x05R\n" +
	"sourceNode\x12\x1b\n" +
	"\tbin_value\x18\x03 \x01(\x05R\bbinValue\"o\n" +
	"\rAuxSetMessage\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\x05R\n" +
	"sourceNode\x12\"\n" +
	"\x04view\x18\x03 \x01(\x0e2\x0e.typedefs.ViewR\x04view\"\xae\x01\n" +
	"\vABAEnvelope\x12,\n" +
	"\x06bv_msg\x18\x01 \x01(\v2\x13.typedefs.BVMessageH\x00R\x05bvMsg\x12/\n" +
	"\aaux_msg\x18\x02 \x01(\v2\x14.typedefs.AuxMessageH\x00R\x06auxMsg\x129\n" +
	"\vaux_set_msg\x18\x03 \x01(\v2\x17.typedefs.AuxSetMessageH\x00R\tauxSetMsgB\x05\n" +
	"\x03msg*s\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tUNDECIDED\x10\x01\x12\b\n" +
	"\x04ZERO\x10\x02\x12\a\n" +
	"\x03ONE\x10\x03\x12\x12\n" +
	"\x0eUNDECIDED_ZERO\x10\x04\x12\x11\n" +
	"\rUNDECIDED_ONE\x10\x05\x12\f\n" +
	"\bZERO_ONE\x10\x06B\fZ\n" +
	"./typedefsb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messages_proto_goTypes = []any{
	(View)(0),             // 0: typedefs.View
	(*BVMessage)(nil),     // 1: typedefs.BVMessage
	(*AuxMessage)(nil),    // 2: typedefs.AuxMessage
	(*AuxSetMessage)(nil), // 3: typedefs.AuxSetMessage
	(*ABAEnvelope)(nil),   // 4: typedefs.ABAEnvelope
}
var file_messages_proto_depIdxs = []int32{
	0, // 0: typedefs.AuxSetMessage.view:type_name -> typedefs.View
	1, // 1: typedefs.ABAEnvelope.bv_msg:type_name -> typedefs.BVMessage
	2, // 2: typedefs.ABAEnvelope.aux_msg:type_name -> typedefs.AuxMessage
	3, // 3: typedefs.ABAEnvelope.aux_set_msg:type_name -> typedefs.AuxSetMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*ABAEnvelope_BvMsg)(nil),
		(*ABAEnvelope_AuxMsg)(nil),
		(*ABAEnvelope_AuxSetMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
