name: RBC Test

on:
  push:
    branches: [ rbc ]
  pull_request: 
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.platform}}
    env:
      LLVL: trace
    steps:
      - name: Use Go = 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '=1.23'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          # Pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create temp directory
        run: |
          mkdir -p ./${{ github.run_attempt }}
      
      - name: run RBC Bracha tests
        run: go test -json -v -race -run TestBrachaRBC ./rbc/bracha | gotestfmt

      - name: run RBC FourRounds tests
        run: go test -json -timeout 20m -v -race -run TestFourRoundsRBC ./rbc/fourrounds | gotestfmt
