name: RBC Test

on:
  push:
    branches: [ rbc ]
  pull_request: 
    types:
      - opened
      - synchronized
      - reopened
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.platform}}
    env:
      LLVL: trace
    steps:
      - name: Use Go = 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '=1.23'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          # Pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create temp directory
        run: |
          mkdir -p ./${{ github.run_attempt }}
      
      - name: run RBC Bracha tests
        run: |
          set -euo pipefail
          go test -json -v -race -run ./rbc/bracha 2>&1 | tee ./${{ github.run_attempt }}/rbctest-brac.log | gotestfmt

      - name: run RBC FourRounds tests
        run: |
          set -euo pipefail
          go test -json -v -race -run ./rbc/fourRounds 2>&1 | tee ./${{ github.run_attempt }}/rbctest-four.log | gotestfmt
      # Upload formatted logs
      - name: Upload bracha test log
        uses: actions/upload-artifact@v4
        with:
          name: test-bracha-log
          path: ./${{ github.run_attempt }}/rbctest-brac.log.log
          if-no-files-found: error

      - name: Upload 4Rounds test log
        uses: actions/upload-artifact@v4
        with:
          name: test-4rounds-log
          path: ./${{ github.run_attempt }}/rbctest-four.log
          if-no-files-found: error
    
      
    
